<template>
    <div>
        <table border="1" style="border-collapse: collapse">
            <tr>
                <th>残日数</th>
                <th>付与日数</th>
                <th>取得日数</th>
                <th>時間取得（年）</th>
                <th>時間取得限度（年）</th>
            </tr>
            <tr>
                <th>有給休暇</th>
                <td>日数</td>
                <td>日数</td>
                <td>日数</td>
                <td>日数</td>
            </tr>
        </table>
    </div>
</template>
