<template>
    <table border="1" style="border-collapse: collapse">
        <thead>
            <tr>
                <th colspan="8">勤怠データ確認</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>出勤</th>
                <td>5</td>
                <th>振休</th>
                <td>0</td>
                <th>基本</th>
                <td>40:00</td>
                <th>----</th>
                <td>----</td>
            </tr>
            <tr>
                <th>欠勤</th>
                <td>0</td>
                <th>代休</th>
                <td>0</td>
                <th>残業</th>
                <td>00:00</td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th>休出</th>
                <td>0</td>
                <th>遅早</th>
                <td>0</td>
                <th>深夜</th>
                <td>00:00</td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th>有給</th>
                <td>2</td>
                <th></th>
                <td></td>
                <th>深夜残</th>
                <td>00:00</td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th>時有給</th>
                <td>00:00</td>
                <th></th>
                <td></td>
                <th>遅早</th>
                <td>00:00</td>
                <th></th>
                <td></td>
            </tr>
            <tr>
                <th>特休</th>
                <td>0</td>
                <th></th>
                <td></td>
                <th></th>
                <td></td>
                <th></th>
                <td></td>
            </tr>
        </tbody>
    </table>
</template>
